# Generated by Django 5.2.5 on 2025-08-26 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_uid', models.CharField(max_length=20, unique=True, verbose_name='RFID UID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('department', models.CharField(max_length=100, verbose_name='Цех')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Табельный номер')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('hire_date', models.DateField(verbose_name='Дата приема')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_uid', models.CharField(max_length=20, verbose_name='RFID UID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время касания')),
                ('device_id', models.CharField(default='ESP32-001', max_length=50, verbose_name='Устройство')),
                ('success', models.BooleanField(default=True, verbose_name='Успешно')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Касание карты',
                'verbose_name_plural': 'Касания карт',
                'ordering': ['-timestamp'],
            },
        ),
    ]
