# Generated by Django 5.2.5 on 2025-09-13 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_cardaccess_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='employee',
            name='inn',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать 10 или 12 цифр', regex='^\\d{10}$|^\\d{12}$')], verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Холост/Не замужем'), ('married', 'Женат/Замужем'), ('divorced', 'Разведен(а)'), ('widowed', 'Вдовец/Вдова')], max_length=20, verbose_name='Семейное положение'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Номер паспорта должен содержать 6 цифр', regex='^\\d{6}$')], verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_series',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message="Серия паспорта должна быть в формате: 'N-XX'", regex='^[A-Z]-[A-Z]{2}$')], verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='employee',
            name='snils',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='СНИЛС должен содержать 11 цифр', regex='^\\d{11}$')], verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rfid_uid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RFID UID'),
        ),
    ]
