# Generated by Django 5.2.5 on 2025-09-13 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_address_employee_birth_date_employee_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='passport_issue_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='inn',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать 10 или 12 цифр.', regex='^\\d{10}$|^\\d{12}$')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_issued_by',
            field=models.TextField(blank=True, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Серия паспорта должна быть в формате: I-AH, II-MR и т.д.', regex='^[IVXLC]-[A-Z]{2}$')], verbose_name='Серия паспорта'),
        ),
    ]
