# Generated by Django 5.2.5 on 2025-09-14 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_passport_issue_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('entry_time', models.TimeField(blank=True, null=True, verbose_name='Время прихода')),
                ('exit_time', models.TimeField(blank=True, null=True, verbose_name='Время ухода')),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Отработано часов')),
                ('status', models.CharField(choices=[('present', 'Присутствует'), ('absent', 'Отсутствует'), ('sick', 'Больничный'), ('vacation', 'Отпуск'), ('partial', 'Частичный день'), ('late', 'Опоздание'), ('early_leave', 'Ранний уход')], default='present', max_length=20, verbose_name='Статус')),
                ('entry_device', models.CharField(blank=True, max_length=50, verbose_name='Устройство входа')),
                ('exit_device', models.CharField(blank=True, max_length=50, verbose_name='Устройство выхода')),
                ('is_manual_entry', models.BooleanField(default=False, verbose_name='Ручной ввод')),
                ('is_corrected', models.BooleanField(default=False, verbose_name='Скорректировано HR')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Рабочее время',
                'verbose_name_plural': 'Рабочее время',
                'ordering': ['-date', 'employee__last_name'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
