# Generated by Django 5.2.5 on 2025-09-26 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_worktimeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rfid_uid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='RFID должен содержать 8-14 символов в формате HEX (0-9, A-F)', regex='^[0-9A-F]{8,14}$')], verbose_name='RFID UID'),
        ),
    ]
