# Generated by Django 5.2.5 on 2025-08-28 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TileProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.IntegerField(default=0)),
                ('press_name', models.CharField(default='PH6500', max_length=50)),
                ('tile_size', models.CharField(default='40x80 см', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
