# Generated by Django 5.2.5 on 2025-08-28 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('weight_per_piece', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Вес штуки (кг)')),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за штуку')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тип кафеля',
                'verbose_name_plural': 'Типы кафеля',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество штук')),
                ('tile_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warehouse.tiletype', verbose_name='Тип кафеля')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Расход')], max_length=3, verbose_name='Операция')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время')),
                ('tile_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.tiletype', verbose_name='Тип кафеля')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
    ]
