# Generated by Django 5.2.5 on 2025-09-29 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название станка')),
                ('esp32_id', models.CharField(max_length=50, unique=True, verbose_name='ID ESP32')),
                ('meters_per_pulse', models.DecimalField(decimal_places=3, default=0.5, max_digits=10, verbose_name='Метров за импульс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('status', models.CharField(choices=[('idle', 'Простой'), ('working', 'Работает'), ('maintenance', 'В ремонте'), ('stopped', 'Остановлен')], default='idle', max_length=20, verbose_name='Статус')),
                ('current_pulse_count', models.IntegerField(default=0, verbose_name='Текущий счетчик импульсов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='Текущий оператор')),
            ],
            options={
                'verbose_name': 'Станок',
                'verbose_name_plural': 'Станки',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_time', models.DateTimeField(verbose_name='Время вызова')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало ремонта')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Окончание ремонта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Завершен')], default='pending', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание проблемы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lohia_monitor.machine', verbose_name='Станок')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_calls', to='employees.employee', verbose_name='Мастер')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Вызов мастера',
                'verbose_name_plural': 'Вызовы мастера',
                'ordering': ['-call_time'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало смены')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Окончание смены')),
                ('total_pulses', models.IntegerField(default=0, verbose_name='Общее количество импульсов')),
                ('total_meters', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий метраж')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена')], default='active', max_length=20, verbose_name='Статус смены')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lohia_monitor.machine', verbose_name='Станок')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PulseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время')),
                ('pulse_count', models.IntegerField(verbose_name='Количество импульсов')),
                ('total_pulses', models.IntegerField(verbose_name='Общее количество импульсов')),
                ('meters_produced', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Произведено метров')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lohia_monitor.machine', verbose_name='Станок')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lohia_monitor.shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Лог импульсов',
                'verbose_name_plural': 'Логи импульсов',
                'ordering': ['-timestamp'],
            },
        ),
    ]
