# Generated by Django 5.2.5 on 2025-10-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lohia_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='gear_box_ratio',
            field=models.DecimalField(decimal_places=2, default=64.0, max_digits=10, verbose_name='Gear box redn ratio'),
        ),
        migrations.AddField(
            model_name='machine',
            name='p_ctrl_ampl',
            field=models.IntegerField(default=2, verbose_name='P-Ctrl. Ampl.'),
        ),
        migrations.AddField(
            model_name='machine',
            name='roller_diameter_cm',
            field=models.DecimalField(decimal_places=2, default=16.7, max_digits=10, verbose_name='Roller Dia. (cm)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='sprocket_gear_box',
            field=models.IntegerField(default=23, verbose_name='Sprocket gear box'),
        ),
        migrations.AddField(
            model_name='machine',
            name='sprocket_takeup_roller',
            field=models.IntegerField(default=41, verbose_name='Sprocket takeup roller'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmit_pulse',
            field=models.IntegerField(default=40, verbose_name='Transmit Pulse'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='meters_per_pulse',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10, verbose_name='Метров за импульс (вычисляемое)'),
        ),
    ]
