# Generated by Django 5.2.3 on 2025-10-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_user'),
        ('lohia_monitor', '0002_machine_gear_box_ratio_machine_p_ctrl_ampl_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['esp32_id', 'is_active'], name='machine_esp32_active'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['current_operator', 'status'], name='machine_op_status'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['updated_at'], name='machine_updated'),
        ),
        migrations.AddIndex(
            model_name='pulselog',
            index=models.Index(fields=['machine', 'timestamp'], name='pulse_mach_time'),
        ),
        migrations.AddIndex(
            model_name='pulselog',
            index=models.Index(fields=['shift', 'timestamp'], name='pulse_shift_time'),
        ),
        migrations.AddIndex(
            model_name='pulselog',
            index=models.Index(fields=['timestamp'], name='pulse_timestamp'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['machine', 'operator', 'status'], name='shift_mach_op_status'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['start_time'], name='shift_start_time'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['status', 'machine'], name='shift_status_mach'),
        ),
    ]
